namespace StorageFlow.Abstractions.Interfaces;

/// <summary>
/// Validates object keys generated by naming strategies.
/// </summary>
public interface IObjectKeyValidator
{
    /// <summary>
    /// Validates <paramref name="objectKey"/> and throws a storage naming exception when invalid.
    /// </summary>
    void Validate(string objectKey);
}
